# Generated by Django 5.1.2 on 2024-10-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventoapp', '0004_tipoevento_lugar_detallelugar_evento_tipoevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
